### ISSUE TITLE
Application form - use radio instead of dropdown for support type

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#162]
Specify the widget for `support_type` in the modelform: [`sjfnw/grants/modelforms.py`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/modelforms.py#L103)

[Django widget docs](https://docs.djangoproject.com/en/1.8/ref/forms/widgets/)

Current widget shown in form

<img width="742" alt="screen shot 2016-10-01 at 12 49 15 pm" src="https://cloud.githubusercontent.com/assets/1279315/19016646/91417d4c-87d5-11e6-801e-23aec10c52ff.png">

Expanded:

<img width="249" alt="screen shot 2016-10-01 at 12 49 30 pm" src="https://cloud.githubusercontent.com/assets/1279315/19016648/9538a358-87d5-11e6-8228-eedf934d2d5b.png">

To see it locally:
1. You need to be registered as an Organization (instructions [here](http://aisapatino.github.io/sjfnw/getting-started/local-server/))
2. You need an open grant cycle - create one if needed at [http://localhost:8080/admin/grants/grantcycle/add/](http://localhost:8080/admin/grants/grantcycle/add/) (enter any url for cycle info page - you can use `http://socialjusticefund.org/grant-app/criminal-justice-grant-2016`)
3. Go to [http://localhost:8080/apply/](http://localhost:8080/apply/)
4. You should see an "Apply" link - click that
5. Click "Continue to application" button

**Comment by bookstein** [comment]
@aisapatino Please add a link to the specific file or template where you want this dropdown converted to radio!

**Comment by aisapatino** [comment]
Added link to where the change needs to be made

**Comment by noelledaley** [comment]
@aisapatino Is there a particular view where we can easily see this dropdown in action? I've tried to access the grant application at http://localhost:8080/apply/nr but I need to register a separate account and the new account isn't saving.
