### ISSUE TITLE
Show 'asked' in admin donor view

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#682]
via Sunny
>Mijo just mentioned to me that she wants to see a column for "Asked" in the Donor view. Currently it's showing "Talked" and if it's one or the other she'd prefer Asked. If we can do both, great.

**Comment by tarhata** [comment]
I think this already exists? I think this what you're referring to.

![screenshot from 2015-04-13 20 45 10](https://cloud.githubusercontent.com/assets/8212941/7130018/0a256a8e-e21e-11e4-9d0e-7092f6503b2f.png)

**Comment by aisapatino** [comment]
Oh, you're right! Will close this then
