### ISSUE TITLE
Matching option for gifts

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#703]
>Question from Mijo Lee and Kylie: Can we have a checkbox "this gift will be matched by the donor's employer" + $ amount or ratio + employer's name

https://app.asana.com/0/5175284945766/24876821467294

**Due 3/18**

- [x] Update donor model with new fields: `match_expected`, `match_company`, `match_received`
- [x] Update local DB with new fields
- [x] Update `StepDoneForm`: add fields
- [x] Update validation
- [x] Update `complete_step.html` template: add fields
- Update tests:
  - [x] Run tests and update whatever is failing
  - [x] New tests: Error if they enter one of match expected or company name without the other
- [x] Admin display
  - [x] Visible, editable sortable in list view
  - [x] Visible & editable in change view
- [x] Progress display for members (charts)
- [x] Display in donor details
- [x] Affects progress charts for group

Once everything looks solid:
  - [ ] Update production DB
  - [ ] Deploy
  - [ ] Test manually

Stretch goals, may split into follow up tickets:
- Possibly add filter to admin if Sunny indicates
- Allow percentage or amount input for `match_expected`
    - New tests: Valid & invalid match amounts/percentages

Refactoring complete step form into 2 steps will be a separate issue because of this needing to be done asap

**Comment by aisapatino** [comment]
Entered by members - match amount, company name
Maybe suggest putting in notes if SJF needs to follow up with employer
Count toward promise
Extra gift field for staff entering match

**Comment by aisapatino** [comment]
@tarhata This could be a good one for us to work on together. It's mainly a UX issue and I can help with coding as needed.

We want to keep the flow pretty simple so it feels easy to use for members. This is the most complex form already, and this change will add two new fields and possibly some text. So I'd be curious to get your feedback on the appearance and layout and whatnot.

You can try it out by going to `/fund`, create a donor &/or step if needed, then hit the 'complete' link. Select 'Promised' under 'Response'. You'll see a new section of the form slide in, asking for promise-related info. These new fields will be part of that, going with the promise amount field.

Let's plan to talk about this on Thursday if there's time.

FYI, here's what the fully expanded form looks like. I can see a few display bugs already (alignment is pretty wonky). I'd like to fix it up while we're adding new stuff to it.

![sjf-pc-complete-step](https://cloud.githubusercontent.com/assets/1279315/6339619/7413453e-bb6c-11e4-972c-16599a768480.png)

**Comment by tarhata** [comment]
I think I remember this being discussed during our meeting with Sunny two Fridays ago. There's definitely already a lot going on in this form and as someone still learning how members use project central to keep track of their fundraising, I'm curious to how users react when filling out this page.

**Comment by tarhata** [comment]
Check commits and comments on #738

**Comment by aisapatino** [comment]
Done! :tada: closing

**Comment by tarhata** [comment]
::star2:: ::satisfied::::star2::
