### ISSUE TITLE
Add link to eligibility survey to grants

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#715]
Add this link to org login page & home page

http://www.surveymonkey.com/s/LJLB7Z8

see https://app.asana.com/0/5175284945766/18586670043046

**Comment by tarhata** [comment]
Further clarification from Sunny:

"This is a quick fix once you know how to edit this page for the grantees. 

The attached image above is the view that grantees have when they log in before submitting their grant applications. The change I want is to add a link to the eligibility survey with the following language:

If you have not received a Social Justice Fund grant before, please fill out this brief pre-application questionnaire before you begin your application.
http://www.surveymonkey.com/s/LJLB7Z8 (that's the link)"

**Comment by aisapatino** [comment]
Deployed! :+1: Closing.
