### ISSUE TITLE
500 when entering negative amount in edit contact form

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#737]
When editing a contact, if I enter a negative number in the `amount` field, I get a 500. The logged error is:
`Warning: Out of range value for column 'amount' at row 1`

So the code is trying to insert the negative number into the database, and the db throws an error because it only accepts positives. This should be caught by form validation so the user gets a form error instead of an `Internal Server Error` page.

- The form used is `sjfnw/fund/modelforms/py` [`DonorForm`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/fund/modelforms.py#L33)
- The `amount` field uses an [`IntegerCommaField`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/forms.py#L45).
- See [`custom_integer_field`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/fund/modelforms.py#L13) where that is set
- Note that `IntegerCommaField` has a `min_value` option but it's not being set for this form.

Some more background:
- `__init__` is what gets called when you initialize a class. (i.e. [this line](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/fund/modelforms.py#L15) triggers this [`__init__`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/forms.py#L56) function
- You don't need to worry about `formfield_callback` much, but the gist is that you pass it a function that you want to call whenever a form field is being created for that form. Then you have the opportunity to use the default field (by returning `field.formfield()`) or to return a custom field as we're doing for the `amount` field.
- `**kwargs` can be accessed as just `kwargs` (a dictionary) inside a function that has it in the signature. [Here](https://github.com/aisapatino/sjfnw/blob/cae19e6b70e50c0c79cec3d3fe03e41810b0c748/sjfnw/grants/modelforms.py#L88) is an example of how to add something to `kwargs` before passing it on.

(Post questions if you have any questions about the above!)

##### To do
- [x] Brainstorm how you might solve this; post here for review
- [x] Make the code change
- [x] Run local server and verify that it works
- [x] Write a test to verify that it works
  - There are no tests for this form yet, so I can help you get started once you get to this step.
- [x] Open a PR!

**Comment by aisapatino** [comment]
Just noticed that this doesn't happen on the live site - if you put in a negative number it gets saved as `0` without any notice/error/etc. Not sure why; the `amount` column in `fund_donor` is `int(10) unsigned` in both cases. Still worth fixing I think; it's a small change to configure the form field. It does consistently throw an error locally, for me at least.

**Comment by tarhata** [comment]
Ok, after some reading and sleeping on it (I'm pretty sure I dreamt about this!), and here's what I think is going on.

My understanding of how this works:
- Django's built-in form fields already have form validation built in
- Since `IntegerCommaField` (and `PhoneNumberField`) is a new form field created in `sjfnw/sjfnw/forms.py` , we have to write our own form validation
- The edit contact form is submitted using an AJAX request. A raised `ValidationError` would normally stop the form `POST` process. Since it's no errors are raised, the form is "successfully" submitted and a server 500 error occurs since the `amount` value is an inherently invalid value for the model.

QUESTIONS:
- Why is a ModelForm used for `DonorForm` but not `StepDoneForm`?
- When do you raise a `ValidationError` vs just display an error through `self.errors`? Or are you supposed to do both (because form validation ensures that the value is valid, while error messages just prompt the user)? Either scenario stops the form from POSTING, so isn't it redundant?
- `amount` is already defined to be a `PositiveIntegerField` in the model. If we had been using the built-in `IntegerField`, wouldn't django have handled all the validation and error displaying? 
- Are modelforms just specialized forms tied to models? From what I've read modelforms are shortcuts to creating form fields from models.
- Also, why is the `min_value` you pointed out in the `IntegerCommaField` not used? I do see a `min_value` in `MassDonorForm`:
```
class MassDonor(MassDonorPre):
  amount = IntegerCommaField(label='*Estimated donation ($)',
                             min_value=0,
                             widget=forms.TextInput(attrs={'class':'width-75'}))
```

SOLUTION?
I looked at the `StepDoneForm` and am thinking there needs to be something like this for the `DonorForm`:

From StepDoneForm:
```  
promised_amount = IntegerCommaField(
      required=False, min_value=0,
      error_messages={'min_value': 'Promise amounts cannot be negative'},
      widget=forms.TextInput(attrs={'size':10}))
```

**Comment by aisapatino** [comment]
Great :+1: Your solution looks good -passing `min_value` in when we instantiate `IntegerCommaField`, like the examples you posted.

----

>Django's built-in form fields already have form validation built in

Correct. On [this page](https://docs.djangoproject.com/en/1.5/ref/forms/fields/#built-in-field-classes) they specify what each field type validates. You can always add extra validation to any field.

>Since IntegerCommaField (and PhoneNumberField) is a new form field created in sjfnw/sjfnw/forms.py , we have to write our own form validation

Correct; the base `Field` class doesn't validate anything. Since I based `IntegerCommaField` closely off of `IntegerField` (actually I think I just copied the code and edited it), it's set up for some basic validation already via the optional `min_value` and `max_value` parameters at initialization.

>The edit contact form is submitted using an AJAX request. A raised ValidationError would normally stop the form POST process. Since it's no errors are raised, the form is "successfully" submitted and a server 500 error occurs since the amount value is an inherently invalid value for the model.

Yep. It doesn't exactly stop the post process, but it takes a different path through the code (which is probably what you meant, anyway). If [`form.is_valid()`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/fund/views.py#L767) returns `False`, it won't save, and instead will re-render the template with the form which contains error messages. The 500 is because mysql throws an error trying to save a negative number to an `unsigned` column.

>QUESTIONS:
Why is a ModelForm used for DonorForm but not StepDoneForm?

Model form is used when the form is editing a single model. It's basically a shortcut - it automatically creates form fields based on model fields, and automatically saves the model when the form is saved. Step completion can edit a step, edit the contact, and create a new step, all in the same form. Since it doesn't map to a single model we can't use a modelform for that.

>When do you raise a ValidationError vs just display an error through self.errors? Or are you supposed to do both (because form validation ensures that the value is valid, while error messages just prompt the user)? Either scenario stops the form from POSTING, so isn't it redundant?

It's inconsistent throughout because I didn't know what I was doing but also because the Django setup in 1.5 is not ideal.
- You don't need both, just one or the other. The purpose of an error is
  - Ensure that `form.is_valid()` does not pass
  - Associate an error with the given field (if applicable) so it can be displayed in the right place.
- `ValidationError` is the better way to do it, because `self._errors` is accessing what's meant to be an internal property of the `Form` class (indicated by the leading underscore). So it's a bit hacky.
- _However_, `ValidationError` doesn't allow you specify the field. So you have to call it in the `clean` method of a specific field, or in a `clean_<fieldname>` method, if you want it tied to a field (which we generally do, for display purposes)
- Thus when we're in a _form's_ `clean` method we're probably using `self._errors` for now.
- Here's what [Django 1.5 says about it](https://docs.djangoproject.com/en/1.5/ref/forms/validation/):

  > Note that any errors raised by your Form.clean() override will not be associated with any field in particular. They go into a special “field” (called __all__), which you can access via the non_field_errors() method if you need to. If you want to attach errors to a specific field in the form, you will need to access the _errors attribute on the form, which is described later.
- In 1.7 they introduce an awesome [`Form.add_error`](https://docs.djangoproject.com/en/1.7/releases/1.7/#form-add-error) method to end all this nonsense. That's noted in the [upgrade Django ticket](https://github.com/aisapatino/sjfnw/issues/691)

>amount is already defined to be a PositiveIntegerField in the model. If we had been using the built-in IntegerField, wouldn't django have handled all the validation and error displaying?

Yes, if we let the modelform figure out the field it would enforce the minimum. But since we defined the form field, it's not referencing the model field at all and thus doesn't enforce the positive part automatically. It was an SJF requirement a while back that we allow commas in number fields, which is the only reason we're not using the default. We could probably safely require a positive number within `IntegerCommaField` itself, we'd just have to verify that all the places that use it only accept positive numbers.

>Are modelforms just specialized forms tied to models? From what I've read modelforms are shortcuts to creating form fields from models.

Yep, for creating fields and also for saving.

> Also, why is the min_value you pointed out in the IntegerCommaField not used? I do see a min_value in MassDonorForm:

The `min_value` in `IntegerCommaField` is a keyword parameter that defaults to `None`

```python
def __init__(self, max_value=None, min_value=None, *args, **kwargs):
```

With `MassDonorForm`, it works and validates because we're passing a value in. For `DonorForm`, we're just doing

```python
    return IntegerCommaField(**kwargs)
```

And `kwargs` doesn't automatically have a `min_value` because it's not referencing the model at all (since it's a regular form).

------

Hope that helps and isn't total information overload! Those are good questions. Feel free to ask for clarification etc. I'm checking off the first box for you :star2:

**Comment by tarhata** [comment]
Yay! Guess I shouldn't second guess myself so much. I've been running
around most of today, but will fix the code and hopefully commit it by the
evening.
