### ISSUE TITLE
Space in fiscal sponsor field makes adding a fiscal sponsor letter mandatory

### ISSUE THREAD

**Issue by tarhata** [aisapatino/sjfnw#756]
Sunny got a call from an organization wondering why they were required to upload a fiscal sponsor letter if they didn't indicate they had one. Turned out the org had accidentally input a space ` ` in the `Organization or Fiscal Sponsor EIN` field.  Wasn't obvious that there was a space there (field looked empty) until Sunny signed into the org application and tabbed through the fields.

Should add a check for alphanumeric characters if there is input in the field.

**Comment by aisapatino** [comment]
Related to #425. But we can prioritize doing this field in particular.

**Comment by aisapatino** [comment]
Closing; see #425
