### ISSUE TITLE
Grant cycle column in admin giving project grant page shows year twice

### ISSUE THREAD

**Issue by tarhata** [aisapatino/sjfnw#757]
This doesn't happen locally. Seems like it only happens for some Grant cycles.

![image](https://cloud.githubusercontent.com/assets/8212941/7528602/69706330-f4df-11e4-8cad-5c7430fc29e7.png)

**Comment by aisapatino** [comment]
Right [here](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/admin.py#L380) - we're adding the year, but most grant cycles are named with the year as part of the title, so it's not necessary.

**Comment by tarhata** [comment]
Ok, I thought something like that was the case. I asked Sunny about it and they hadn't noticed it before, so I was worried I had broke something!
