### ISSUE TITLE
Cannot view existing grants from grant link in Giving Project admin site

### ISSUE THREAD

**Issue by tarhata** [aisapatino/sjfnw#759]
Was testing all the changes I made for multi-year grants and came across this bug. You can't view already existing grants in the `Grant link` column. As you can see in the screenshots, a grant already exists for Causa Oregon, but the Giving Project Admin page still shows an `Add grant` link. At first I thought I had introduced it locally, but it exists even on the live site!

![grant link bug - giving project admin display](https://cloud.githubusercontent.com/assets/8212941/7662685/774c9a24-fb14-11e4-89b0-51dbd66c02a1.png)

![grant link bug - giving project grant admin](https://cloud.githubusercontent.com/assets/8212941/7662689/7c606478-fb14-11e4-850a-8e71423b91ec.png)

**Comment by tarhata** [comment]
Tried testing again, and sometimes `Projectapp` will show `(None)` after clicking the `Add grant` link. This is what happened to Sunny a few weeks back.

I think the code breaks when it tries to execute the `grant_link` method in [`fund/admin.py`] (https://github.com/aisapatino/sjfnw/blob/1c537494abb7892163ecedd95a2ae834f8b0132f/sjfnw/fund/admin.py#L157). I just went over boolean truth tables with one of my students, so maybe it has something to do with how it's evaluating the second if-statement?

I noticed that it is written differently than the `granted` method in [`grants/admin.py`](https://github.com/aisapatino/sjfnw/blob/1c537494abb7892163ecedd95a2ae834f8b0132f/sjfnw/grants/admin.py#L204) so I changed the code on my local server to match it and made an overarching `if obj` if-statement. So it looks like this now:

```
  def grant_link(self, obj):
    if obj:
      if hasattr(obj, 'givingprojectgrant'):
        award = obj.givingprojectgrant
        return ('<a href="/admin/grants/givingprojectgrant/{}/">View grant</a>'
                .format(award.pk))
      if hasattr(obj, 'screening_status') and obj.screening_status > 80:
        return ('<a href="/admin/grants/givingprojectgrant/add/?projectapp={}">Add grant</a>'
                .format(obj.pk))
    return ''
  grant_link.allow_tags = True
```

**Comment by aisapatino** [comment]
yikes, this is a recent addition and i don't seem to have been paying much attention when i did it. i'll put in a PR

the `ProjectApp` being `(None)` is a separate issue - I reopened #698. so far the links are working fine for me but i'll take a closer look once i get the PR up
