### ISSUE TITLE
Admin - list attachments on grant app page

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#799]
A grant application has many file fields; these aren't shown on the admin site directly and can only be seen in the grant app reading view.

When files aren't displaying properly in that view, it's hard for staff to tell why - if they could see the filename & have a way to download the files directly that would help in those cases.

- [ ] Add `FileFields` to the grant application admin page (see [model FileFields](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/models.py#L449), [sjfnw/grants/admin.py](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/admin.py#L311))
- [ ] They should all be read-only
- [ ] If easy to do, clicking on a filename should download. Should be able to do this using [`serve_app_file`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/views.py#L831) - if this looks complicated, skip it or check with @aisapatino -- [stretch goal]
- [ ] Make it an expandable section, hidden by default (see the "application contact info" section for an example of that)
- [ ] Verify that it works locally
- [ ] Write at least one simple test just loading the admin page and verifying that certain strings are/are not part of the html response. (Example - [grants admin inline tests](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/tests/test_admin.py#L10))

https://app.asana.com/0/5175284945766/61528230471183

**Comment by bookstein** [comment]
Affects these URLs:
admin/grants/grantapplication/{id}
admin/grants/view/{id}

@aisapatino We may need to add files to sample data for local dev.

**Comment by bookstein** [comment]
Solution in progress for adding file names to `admin/grants/view/{id}`.

Ie: http://localhost:8080/grants/view/164
