### ISSUE TITLE
Add search to admin GPG list

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#802]
GPG = giving project grant

Admin page is at [/admin/grants/givingprojectgrant/](http://localhost:8080/admin/grants/givingprojectgrant/) and has no search bar.
It is configured in [`sjfnw/grants/admin.py`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/admin.py#L381)

Should be able to search at least by organization name. Grant cycle and/or giving project would be good too.

See [django docs on `search_fields`](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_fields).

**Comment by bookstein** [comment]
This could be a one-line change.

**Comment by bookstein** [comment]
PR opened! https://github.com/aisapatino/sjfnw/pull/806

**Comment by aisapatino** [comment]
Done in 6986efd
