### ISSUE TITLE
Omit non-ascii punctuation from word counts

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#822]
### Background

Grant application enforces word limit for several fields.

On the server, see [`WordLimitValidator`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/models.py#L202) and its usage further down the page.

For client-side validation, the limits are added to the form html with a `data` attribute - see [`sjfnw/grants/modelforms.py`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/modelforms.py#L93). Then the js function [`updateWordCount`](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/static/js/forms.js#L73) updates the word count indicator next to each word-limited field.

Note that the server-side validation is what controls whether the form can successfully be submitted, and any post-submit error messages. Client-side js is just for user convenience so they can see how they're doing on word count without having to submit.
### Issue

Currently only strips ascii punctuation, so something like `–` would count as a word.

Branch `word-count-punc` has an update to the python code that excludes most common non-ascii punctuation that we'd expect to be used in a grant app. Needs to have a matching impl in javascript.

Not important to catch 100% of punctuation - but server/client results should match.

**Comment by jessib** [comment]
I don't think I have permission, but can this be marked as closed?
